### ISSUE TITLE
Degrader cutting off vertically for tall maps at y = 4320

### ISSUE THREAD

**Issue by malonkey1** [ParadoxGameConverters/MapDegrader#10]
When I use the Map Degrader for the province map used by Rajas of Asia, the degrader successfully exports, but the provinces.png that it exports doesn't seem to touch any pixels below y = 4319, and I suspect it's due to the large map the mod uses. Attached is the exported provinces.png.

![image](https://user-images.githubusercontent.com/21254333/175783437-2e7f1112-0674-4f30-8192-b3e4399706e6.png)

**Comment by Zemurin** [comment]
For certain types of PNG files, ImageMagick (which we use internally to provide the pixels) returns mangled data. This is an IM bug we cannot control, and the resulting image will be junk.

When that happens, manually convert the provinces.png to provinces.bmp, put it in the same folder, and the MapDegrader will prioritize BMP over PNG.

Sorry for the inconvenience.

PS: I tested that file as BMP and it works as advertised.

**Comment by malonkey1** [comment]
Thanks for letting me know!
